version: '3.5'

services:
  opensearch:
    image: opensearchproject/opensearch:2.17.1
    environment:
      discovery.type: "single-node"
      plugins.security.disabled: true
      OPENSEARCH_JAVA_OPTS: "-Xms4g -Xmx4g"
    ports:
      - "29200:9200"
      - "29300:9300"
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 16Gb
